# Generated by Django 2.0.5 on 2018-05-31 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_import_file_fields_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldSn', models.IntegerField(default=0, help_text='{"form":"F"}', verbose_name='字段序号')),
                ('fieldNameOriginal', models.CharField(help_text='{"form":"F"}', max_length=500, verbose_name='原始字段名')),
                ('fieldNameNew', models.CharField(help_text='{"form":"F"}', max_length=500, verbose_name='新字段名')),
                ('addTime', models.DateTimeField(auto_now_add=True, help_text='{"form":"F"}', verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Excel_import_file_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filenameOriginal', models.CharField(help_text='{"form":"T","require":"T","title":"选择文件","eleType":"file","data":"xls,xlsx"}', max_length=500, verbose_name='原始文件名')),
                ('filenameSaved', models.CharField(help_text='{"form":"F"}', max_length=500, verbose_name='保存文件名')),
                ('tableName', models.CharField(help_text='{"form":"T","require":"T","title":"生成的表名"}', max_length=200, verbose_name='生成的表名（以temp开头）')),
                ('addTime', models.DateTimeField(auto_now_add=True, help_text='{"form":"F"}', verbose_name='添加时间')),
                ('setFieldNameTime', models.DateTimeField(help_text='{"form":"F"}', null=True, verbose_name='设置字段名时间')),
                ('importTime', models.DateTimeField(help_text='{"form":"F"}', null=True, verbose_name='设置字段名时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(help_text='{"form":"T","require":"T","title":"","eleType":"select","data":[{"id":"3","value":"系统级"},{"id":"2","value":"商家级"},{"id":"1","value":"客服级"}]}', verbose_name='等级')),
                ('sellersId', models.IntegerField(db_index=True, default=0, help_text='{"form":"F"}', verbose_name='商家ID')),
                ('parentSellersId', models.IntegerField(default=0, help_text='{"form":"F"}', verbose_name='所属商家ID')),
                ('name', models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"text"}', max_length=100, verbose_name='姓名')),
                ('username', models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"text"}', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"password"}', max_length=50, verbose_name='密码')),
                ('menupur', models.CharField(help_text='{"form":"F"}', max_length=4000, null=True, verbose_name='菜单权限列表')),
                ('status', models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"select","data":[{"id":"T","value":"有效"},{"id":"F","value":"无效"}]}', max_length=1, verbose_name='状态')),
                ('scription', models.CharField(help_text='{"form":"T","require":"F","title":"","eleType":"textarea"}', max_length=4000, null=True, verbose_name='备注')),
                ('uniqueCode', models.CharField(help_text='{"form":"F"}', max_length=4000, null=True, verbose_name='唯一编码')),
                ('addTime', models.DateTimeField(auto_now_add=True, help_text='{"form":"F"}', null=True, verbose_name='添加时间')),
                ('adder', models.IntegerField(default=0, help_text='{"form":"F"}', verbose_name='添加人（User.id）')),
                ('updateTime', models.DateTimeField(help_text='{"form":"F"}', null=True, verbose_name='最后更新时间')),
                ('updater', models.IntegerField(default=0, help_text='{"form":"F"}', verbose_name='最后更新操作人（User.id）')),
                ('deleteTime', models.DateTimeField(help_text='{"form":"F"}', null=True, verbose_name='删除时间')),
                ('deleter', models.IntegerField(default=0, help_text='{"form":"F"}', verbose_name='删除操作人（User.id）')),
            ],
        ),
        migrations.AddField(
            model_name='excel_import_file_main',
            name='adder',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_import_file_main_adder', to='system.User', verbose_name='添加人（User.id）'),
        ),
        migrations.AddField(
            model_name='excel_import_file_main',
            name='importer',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importer', to='system.User', verbose_name='设置字段名时间操作人（User.id）'),
        ),
        migrations.AddField(
            model_name='excel_import_file_main',
            name='setFieldNamer',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setFieldNamer', to='system.User', verbose_name='设置字段名时间操作人（User.id）'),
        ),
        migrations.AddField(
            model_name='excel_import_file_fields_name',
            name='adder',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_import_file_fields_name_adder', to='system.User', verbose_name='添加人（User.id）'),
        ),
        migrations.AddField(
            model_name='excel_import_file_fields_name',
            name='excelImportFileMainId',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excel_import_file_main_id', to='system.Excel_import_file_main', verbose_name='导入文件主表ID'),
        ),
    ]
