# Generated by Django 2.0.5 on 2018-06-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel_import_file_fields_name',
            name='colType',
            field=models.CharField(help_text='{"form":"F"}', max_length=50, null=True, verbose_name='段名类型（从excel判断 ）'),
        ),
        migrations.AlterField(
            model_name='excel_import_file_fields_name',
            name='fieldNameNew',
            field=models.CharField(help_text='{"form":"F"}', max_length=500, verbose_name='新字段名(为空时该字段不导入系统)'),
        ),
    ]
