# Generated by Django 2.0.5 on 2018-06-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180601_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_import_file_fields_name',
            name='adder',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_import_file_fields_name_adder', to='system.User', verbose_name='添加人（User.id）'),
        ),
        migrations.AlterField(
            model_name='excel_import_file_fields_name',
            name='excelImportFileMainId',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_import_file_main_id', to='system.Excel_import_file_main', verbose_name='导入文件主表ID'),
        ),
        migrations.AlterField(
            model_name='excel_import_file_main',
            name='adder',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_import_file_main_adder', to='system.User', verbose_name='添加人（User.id）'),
        ),
        migrations.AlterField(
            model_name='excel_import_file_main',
            name='importer',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importer', to='system.User', verbose_name='设置字段名时间操作人（User.id）'),
        ),
        migrations.AlterField(
            model_name='excel_import_file_main',
            name='setFieldNamer',
            field=models.ForeignKey(help_text='{"form":"F"}', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setFieldNamer', to='system.User', verbose_name='设置字段名时间操作人（User.id）'),
        ),
    ]
