# Generated by Django 2.0.5 on 2018-06-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20180608_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单显示名称')),
                ('grade', models.IntegerField(help_text='{"data":[{"id":"3","text":"系统级"},{"id":"2","text":"商家级"},{"id":"1","text":"客服级"}]}', verbose_name='等级（3：系统级；2：商家级；1：客服级）')),
                ('parentId', models.IntegerField(null=True, verbose_name='父菜单级别ID(0:顶级菜单)')),
                ('linkfile', models.CharField(max_length=100, null=True, verbose_name='链接URL')),
                ('paras', models.CharField(max_length=255, null=True, verbose_name='参数')),
                ('target', models.CharField(max_length=50, null=True, verbose_name='链接打开位置')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='图标类名')),
                ('memo', models.CharField(max_length=4000, null=True, verbose_name='备注')),
                ('ifshow', models.CharField(help_text='{"data":[{"id":"T","text":"显示"},{"id":"F","text":"隐藏"}]}', max_length=1, null=True, verbose_name='是否显示（T：显示；F：隐藏）')),
                ('sorts', models.IntegerField(null=True, verbose_name='排序')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_deleter', to='system.User', verbose_name='删除人（user.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
