# Generated by Django 2.0.5 on 2018-06-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
