# Generated by Django 2.0.5 on 2018-06-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20180611_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_adder', to='system.User', verbose_name='添加人（user.id）'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='deleter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_deleter', to='system.User', verbose_name='删除人（user.id）'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='grade',
            field=models.IntegerField(help_text='{"data":[{"id": "3", "text": "系统级"}, {"id": "2", "text": "商家级"}, {"id": "1", "text": "客服级"}]', verbose_name='等级（3：系统级；2：商家级；1：客服级）'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ifshow',
            field=models.CharField(help_text='{"data":[{"id": "T", "text": "显示"}, {"id": "F", "text": "隐藏"}]', max_length=1, null=True, verbose_name='是否显示（T：显示；F：隐藏）'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_updater', to='system.User', verbose_name='最后修改人（users.id）'),
        ),
    ]
