# Generated by Django 2.0.5 on 2018-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20180612_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='grade',
            field=models.IntegerField(help_text='{"data":[{"id": "3", "text": "系统级"}, {"id": "2", "text": "商家级"}, {"id": "1", "text": "客服级"}]', null=True, verbose_name='等级（3：系统级；2：商家级；1：客服级）'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='菜单显示名称'),
        ),
    ]
