# Generated by Django 2.0.5 on 2018-06-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20180612_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='icon',
            new_name='iconShow',
        ),
    ]
