# Generated by Django 2.0.5 on 2018-06-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20180613_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purname', models.CharField(max_length=50, null=True, verbose_name='权限名称')),
                ('grade', models.IntegerField(help_text='{"data":[{"id": "3", "text": "系统级"}, {"id": "2", "text": "商家级"}, {"id": "1", "text": "客服级"}]', null=True, verbose_name='等级（3：系统级；2：商家级；1：客服级）')),
                ('purcode', models.CharField(max_length=50, null=True, verbose_name='权限代码')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('sorts', models.IntegerField(null=True, verbose_name='排序')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purview_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purview_deleter', to='system.User', verbose_name='删除人（user.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purview_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
