# Generated by Django 2.0.5 on 2018-06-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_purview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syspara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraType', models.CharField(help_text='{"data":[{"id": "系统", "text": "系统"}, {"id": "商家", "text": "商家"}]', max_length=50, null=True, verbose_name='参数类型（系统;商家）')),
                ('paraShow', models.CharField(max_length=200, null=True, verbose_name='参数名称')),
                ('paraTag', models.CharField(max_length=50, null=True, verbose_name='参数标志（用于调用）')),
                ('paraValue', models.CharField(max_length=200, null=True, verbose_name='参数值')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('sorts', models.IntegerField(null=True, verbose_name='排序')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syspara_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syspara_deleter', to='system.User', verbose_name='删除人（user.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syspara_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
