# Generated by Django 2.0.5 on 2018-06-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_syspara'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicMainList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500, null=True, verbose_name='相关关键字')),
                ('dicName', models.CharField(max_length=50, null=True, verbose_name='字典名称')),
                ('dicTag', models.CharField(max_length=50, null=True, verbose_name='字典标志')),
                ('allowSellerOp', models.CharField(help_text='{"data":[{"id": "T", "text": "允许"}, {"id": "F", "text": "不允许"}]', max_length=1, null=True, verbose_name='是否允许商家维护可选项')),
                ('sorts', models.IntegerField(null=True, verbose_name='排序')),
                ('memo', models.CharField(max_length=4000, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deleteTime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainList_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainList_deleter', to='system.User', verbose_name='删除人')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainList_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
