# Generated by Django 2.0.5 on 2018-06-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_dicmainlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicmainlist',
            old_name='deleteTime',
            new_name='deletetime',
        ),
    ]
