# Generated by Django 2.0.5 on 2018-06-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicMainListForSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textForSelect', models.CharField(max_length=50, null=True, verbose_name='可选项显示文本')),
                ('valueForSelect', models.CharField(max_length=50, null=True, verbose_name='可选项值')),
                ('sorts', models.IntegerField(null=True, verbose_name='排序')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainListForSelect_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainListForSelect_deleter', to='system.User', verbose_name='删除人')),
                ('dicMainListId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainListForSelect_dicMainListId', to='system.DicMainList', verbose_name='系统选择项字典表Id（dicMainList.id）')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainListForSelect_sellerId', to='system.Seller', verbose_name='所属商家（0：系统）当允许商家维护选项时，显示可选内容为系统和商家的可选项')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicMainListForSelect_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
