# Generated by Django 2.0.5 on 2018-06-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_dicmainlistforselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=50, null=True, verbose_name='角色名称')),
                ('memo', models.CharField(max_length=200, null=True, verbose_name='说明')),
                ('menuIdList', models.CharField(max_length=500, null=True, verbose_name='访问菜单权限(menu.id,nenu.id,...)')),
                ('sorts', models.IntegerField(null=True, verbose_name='排序')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_deleter', to='system.User', verbose_name='删除人')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_sellerId', to='system.Seller', verbose_name='商家ID（seller.id）（null(0)：系统角色）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
