# Generated by Django 2.0.5 on 2018-07-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purcode', models.CharField(max_length=50, null=True, verbose_name='权限代码')),
                ('purview', models.CharField(max_length=1, null=True, verbose_name='权限')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolePur_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolePur_deleter', to='system.User', verbose_name='删除人')),
                ('roleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolePur_roleId', to='system.Role', verbose_name='权限组')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolePur_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
