# Generated by Django 2.0.5 on 2018-07-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_rolepur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scription',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='menupur',
            new_name='menuIdList',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='parentSellersId',
            new_name='parentSellerId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sellersId',
            new_name='sellerId',
        ),
    ]
