# Generated by Django 2.0.5 on 2018-07-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20180703_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addTime',
            new_name='addtime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deleteTime',
            new_name='deletetime',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updateTime',
            new_name='updatetime',
        ),
    ]
