# Generated by Django 2.0.5 on 2018-07-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20180703_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(help_text='{"form":"T","require":"T","title":"","eleType":"select","data":[{"id":"3","value":"系统级"},{"id":"2","value":"商家级"},{"id":"1","value":"客服级"}]}', null=True, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"text"}', max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parentSellerId',
            field=models.IntegerField(default=0, help_text='{"form":"F"}', null=True, verbose_name='所属商家ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"password"}', max_length=50, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sellerId',
            field=models.IntegerField(db_index=True, default=0, help_text='{"form":"F"}', null=True, verbose_name='商家ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='{"form":"T","require":"T","title":"","eleType":"text"}', max_length=50, null=True, verbose_name='用户名'),
        ),
    ]
