# Generated by Django 2.0.5 on 2018-07-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_userpur'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_deleter', to='system.User', verbose_name='删除人')),
                ('roleId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_roleId', to='system.Role', verbose_name='角色ID（role.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_updater', to='system.User', verbose_name='最后修改人（users.id）')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole_userId', to='system.User', verbose_name='用户ID（user.id）')),
            ],
        ),
    ]
