# Generated by Django 2.0.5 on 2018-07-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_seller_parentsellerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='usersId',
        ),
        migrations.AddField(
            model_name='seller',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_userId', to='system.User', verbose_name='关联系统用户名'),
        ),
    ]
