# Generated by Django 2.0.5 on 2018-07-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20180705_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imformName', models.CharField(max_length=50, null=True, verbose_name='消息名称')),
                ('informTag', models.CharField(max_length=50, null=True, verbose_name='消息标志')),
                ('informInfo', models.CharField(max_length=500, null=True, verbose_name='大致内容')),
                ('condition', models.CharField(max_length=500, null=True, verbose_name='触发条件说明')),
                ('codePosition', models.CharField(max_length=500, null=True, verbose_name='触发代码位置')),
                ('paramMemo', models.CharField(max_length=2000, null=True, verbose_name='参数说明')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informType_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informType_deleter', to='system.User', verbose_name='删除人')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informType_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
