# Generated by Django 2.0.5 on 2018-07-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_informtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysparaForSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraValue', models.CharField(max_length=200, null=True, verbose_name='参数值')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysparaForSeller_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysparaForSeller_deleter', to='system.User', verbose_name='删除人（user.id）')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysparaForSeller_sellerId', to='system.Seller', verbose_name='商家ID（seller.id）')),
                ('sysparaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysparaForSeller_sysparaId', to='system.Syspara', verbose_name='参数ID（syspara.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysparaForSeller_updater', to='system.User', verbose_name='最后修改人（users.id）')),
            ],
        ),
    ]
