# Generated by Django 2.0.5 on 2018-07-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_informtargetuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informtype',
            old_name='imformName',
            new_name='informName',
        ),
    ]
