# Generated by Django 2.0.5 on 2018-07-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_auto_20180715_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortcutMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userShortcutMenu_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userShortcutMenu_deleter', to='system.User', verbose_name='删除人（user.id）')),
                ('menuId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userShortcutMenu_menuId', to='system.Menu', verbose_name='菜单ID（menu.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userShortcutMenu_updater', to='system.User', verbose_name='最后修改人（users.id）')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userShortcutMenu_userId', to='system.User', verbose_name='用户（user.id）')),
            ],
        ),
    ]
