# Generated by Django 2.0.5 on 2018-09-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_usershortcutmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weiXinAppId', models.CharField(max_length=50, null=True, verbose_name='AppId')),
                ('openid', models.CharField(max_length=50, null=True, verbose_name='用户对应公众号唯一标识（微信授权信息）')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='标题')),
                ('info', models.CharField(max_length=8000, null=True, verbose_name='日志内容')),
                ('listsnType', models.CharField(max_length=50, null=True, verbose_name='相关单号类型（订单;发货单）')),
                ('listsn', models.CharField(max_length=50, null=True, verbose_name='相关单号')),
                ('tableName', models.CharField(max_length=200, null=True, verbose_name='相关表名')),
                ('tableId', models.IntegerField(null=True, verbose_name='相关表名ID')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='日志备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysLog_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysLog_deleter', to='system.User', verbose_name='删除人')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysLog_sellerId', to='system.Seller', verbose_name='商家ID')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sysLog_updater', to='system.User', verbose_name='最后修改人（user.id）')),
            ],
        ),
    ]
