# Generated by Django 2.1.2 on 2018-11-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_syslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_adder', to='system.User', verbose_name='添加人（users.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_deleter', to='system.User', verbose_name='删除人')),
                ('sysparaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_sysparaId', to='system.SysparaForSeller', verbose_name='参数ID（para.id）')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_updater', to='system.User', verbose_name='最后修改人（users.id）')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_userId', to='system.User', verbose_name='用户ID（user.id）')),
            ],
        ),
    ]
