# Generated by Django 2.1.2 on 2018-11-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_auto_20181102_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpara',
            name='adder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_adder', to='system.User', verbose_name='添加人（user.id）'),
        ),
        migrations.AddField(
            model_name='userpara',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userpara',
            name='deleter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_deleter', to='system.User', verbose_name='删除人'),
        ),
        migrations.AddField(
            model_name='userpara',
            name='deletetime',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='userpara',
            name='updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userPara_updater', to='system.User', verbose_name='最后修改人（user.id）'),
        ),
        migrations.AddField(
            model_name='userpara',
            name='updatetime',
            field=models.DateTimeField(null=True, verbose_name='最后修改时间'),
        ),
    ]
