# Generated by Django 2.0.5 on 2018-09-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0031_syslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindSeller_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('bindSellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindSeller_bindSellerId', to='system.Seller', verbose_name='被绑定的商家')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindSeller_deleter', to='system.User', verbose_name='删除人')),
                ('sellerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindSeller_sellerId', to='system.Seller', verbose_name='商家')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindSeller_updater', to='system.User', verbose_name='最后修改人（user.id）')),
            ],
        ),
    ]
