# Generated by Django 2.1.2 on 2018-10-23 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_syslog'),
        ('basicInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, verbose_name='中文名')),
                ('e_name', models.CharField(max_length=50, verbose_name='音文名')),
                ('name_head', models.CharField(max_length=10, verbose_name='拼音音头')),
                ('from_country', models.CharField(max_length=50, verbose_name='所属国家')),
                ('info', models.CharField(max_length=500, null=True, verbose_name='说明')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probrand_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probrand_deleter', to='system.User', verbose_name='删除人')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probrand_updater', to='system.User', verbose_name='最后修改人（user.id）')),
            ],
        ),
    ]
