# Generated by Django 2.1.2 on 2018-10-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0004_dicarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicarea',
            name='calsscode',
        ),
        migrations.RemoveField(
            model_name='dicarea',
            name='parentcode',
        ),
        migrations.AddField(
            model_name='dicarea',
            name='parentId',
            field=models.IntegerField(null=True, verbose_name='父类ID'),
        ),
    ]
