# Generated by Django 2.1.2 on 2018-10-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0005_auto_20181026_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicarea',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
