# Generated by Django 2.1.2 on 2018-10-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicInfo', '0006_auto_20181027_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicarea',
            old_name='parent_id',
            new_name='parentId',
        ),
    ]
