# Generated by Django 2.1.2 on 2018-11-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_userpara'),
        ('basicInfo', '0007_auto_20181027_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wareClass', models.CharField(max_length=50, null=True, verbose_name='商品类别')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('abbreviation', models.CharField(max_length=200, verbose_name='产品简介')),
                ('nameE', models.CharField(max_length=50, null=True, verbose_name='英文名字')),
                ('sn', models.CharField(max_length=10, verbose_name='内码')),
                ('wareNo', models.CharField(max_length=50, null=True, verbose_name='货号')),
                ('warePOO', models.CharField(max_length=50, null=True, verbose_name='商品产地')),
                ('ifAccessory', models.CharField(max_length=1, null=True, verbose_name='是否为配件')),
                ('ifIndependentSend', models.CharField(max_length=1, null=True, verbose_name='是否独立包装发货')),
                ('ifSendScan', models.CharField(max_length=1, null=True, verbose_name='是否发货扫描')),
                ('grossWeight', models.IntegerField(null=True, verbose_name='毛重')),
                ('netWeight', models.IntegerField(null=True, verbose_name='净重')),
                ('length', models.IntegerField(null=True, verbose_name='长')),
                ('width', models.IntegerField(null=True, verbose_name='宽')),
                ('height', models.IntegerField(null=True, verbose_name='高')),
                ('lengthOut', models.IntegerField(null=True, verbose_name='外箱长')),
                ('widthOut', models.IntegerField(null=True, verbose_name='外箱宽')),
                ('heightOut', models.IntegerField(null=True, verbose_name='外箱高')),
                ('scription', models.CharField(max_length=500, null=True, verbose_name='商品描述')),
                ('extendPropIdList', models.CharField(max_length=500, null=True, verbose_name='')),
                ('extendPropNameList', models.CharField(max_length=500, null=True, verbose_name='')),
                ('memo', models.CharField(max_length=500, null=True, verbose_name='备注')),
                ('addtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('updatetime', models.DateTimeField(null=True, verbose_name='最后修改时间')),
                ('deletetime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ware_adder', to='system.User', verbose_name='添加人（user.id）')),
                ('brandid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ware_brandid', to='basicInfo.Probrand', verbose_name='品牌')),
                ('deleter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ware_deleter', to='system.User', verbose_name='删除人')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ware_updater', to='system.User', verbose_name='最后修改人（user.id）')),
            ],
        ),
    ]
